export const SAMPLE_HYDERABAD_EVENTS = [
  {
    id: 101,
    name: 'Symphony of the Deccan: Classical Fusion',
    description: 'An acoustic convergence of Carnatic masters and contemporary orchestral strings under the Hyderabad twilight.',
    artist: 'Jayanthi Kumaresh & The Ensemble',
    category: 'Music & Concerts',
    eventDate: '2026-10-18',
    startTime: '19:30:00',
    endTime: '22:00:00',
    status: 'OPEN',
    venue: {
      id: 1,
      name: 'Ravindra Bharathi Auditorium',
      location: 'Saifabad, Hyderabad',
      capacity: 1100,
    },
    price: 999,
  },
  {
    id: 102,
    name: 'The Last Darbar: Heritage Theatre Experience',
    description: 'An evocative historical drama unravelling the untold courts and romances of 18th-century Golconda.',
    artist: 'Qadir Ali Baig Theatre Foundation',
    category: 'Theatre & Performing Arts',
    eventDate: '2026-10-24',
    startTime: '18:00:00',
    endTime: '20:30:00',
    status: 'OPEN',
    venue: {
      id: 2,
      name: 'Chowmahalla Palace Amphitheatre',
      location: 'Old City, Hyderabad',
      capacity: 850,
    },
    price: 1499,
  },
  {
    id: 103,
    name: 'Midnights in Madhapur: Live Stand-up Tour',
    description: 'Observational wit, startup dilemmas, and chaotic Hyderabad city stories packed into an electric two-hour special.',
    artist: 'Rahul Subramanian',
    category: 'Stand-up Comedy',
    eventDate: '2026-10-28',
    startTime: '20:00:00',
    endTime: '22:00:00',
    status: 'OPEN',
    venue: {
      id: 3,
      name: 'Shilpakala Vedika',
      location: 'Hitec City, Hyderabad',
      capacity: 2500,
    },
    price: 799,
  },
  {
    id: 104,
    name: 'Deccan Electronic: Sound & Light Residency',
    description: 'An experimental synthwave and visual art installation in an open-air venue surrounded by Hyderabad boulders.',
    artist: 'Kohra & Dualist Inquiry',
    category: 'Music & Concerts',
    eventDate: '2026-11-05',
    startTime: '21:00:00',
    endTime: '01:00:00',
    status: 'OPEN',
    venue: {
      id: 4,
      name: 'Gachibowli Amphitheatre',
      location: 'Gachibowli, Hyderabad',
      capacity: 3500,
    },
    price: 1299,
  },
];

export const SAMPLE_SEATS = [
  // Row A - VIP
  { id: 1, seatNumber: 'A1', section: 'VIP', seatType: 'VIP Lounge', price: 1999 },
  { id: 2, seatNumber: 'A2', section: 'VIP', seatType: 'VIP Lounge', price: 1999 },
  { id: 3, seatNumber: 'A3', section: 'VIP', seatType: 'VIP Lounge', price: 1999 },
  { id: 4, seatNumber: 'A4', section: 'VIP', seatType: 'VIP Lounge', price: 1999 },
  { id: 5, seatNumber: 'A5', section: 'VIP', seatType: 'VIP Lounge', price: 1999 },
  { id: 6, seatNumber: 'A6', section: 'VIP', seatType: 'VIP Lounge', price: 1999 },
  { id: 7, seatNumber: 'A7', section: 'VIP', seatType: 'VIP Lounge', price: 1999 },
  { id: 8, seatNumber: 'A8', section: 'VIP', seatType: 'VIP Lounge', price: 1999 },
  
  // Row B - Premium
  { id: 9, seatNumber: 'B1', section: 'Premium', seatType: 'Orchestra Front', price: 1499 },
  { id: 10, seatNumber: 'B2', section: 'Premium', seatType: 'Orchestra Front', price: 1499 },
  { id: 11, seatNumber: 'B3', section: 'Premium', seatType: 'Orchestra Front', price: 1499 },
  { id: 12, seatNumber: 'B4', section: 'Premium', seatType: 'Orchestra Front', price: 1499 },
  { id: 13, seatNumber: 'B5', section: 'Premium', seatType: 'Orchestra Front', price: 1499 },
  { id: 14, seatNumber: 'B6', section: 'Premium', seatType: 'Orchestra Front', price: 1499 },
  { id: 15, seatNumber: 'B7', section: 'Premium', seatType: 'Orchestra Front', price: 1499 },
  { id: 16, seatNumber: 'B8', section: 'Premium', seatType: 'Orchestra Front', price: 1499 },

  // Row C - Standard
  { id: 17, seatNumber: 'C1', section: 'Standard', seatType: 'Center Hall', price: 999 },
  { id: 18, seatNumber: 'C2', section: 'Standard', seatType: 'Center Hall', price: 999 },
  { id: 19, seatNumber: 'C3', section: 'Standard', seatType: 'Center Hall', price: 999 },
  { id: 20, seatNumber: 'C4', section: 'Standard', seatType: 'Center Hall', price: 999 },
  { id: 21, seatNumber: 'C5', section: 'Standard', seatType: 'Center Hall', price: 999 },
  { id: 22, seatNumber: 'C6', section: 'Standard', seatType: 'Center Hall', price: 999 },
  { id: 23, seatNumber: 'C7', section: 'Standard', seatType: 'Center Hall', price: 999 },
  { id: 24, seatNumber: 'C8', section: 'Standard', seatType: 'Center Hall', price: 999 },

  // Row D - Balcony
  { id: 25, seatNumber: 'D1', section: 'Balcony', seatType: 'Upper Tier', price: 699 },
  { id: 26, seatNumber: 'D2', section: 'Balcony', seatType: 'Upper Tier', price: 699 },
  { id: 27, seatNumber: 'D3', section: 'Balcony', seatType: 'Upper Tier', price: 699 },
  { id: 28, seatNumber: 'D4', section: 'Balcony', seatType: 'Upper Tier', price: 699 },
  { id: 29, seatNumber: 'D5', section: 'Balcony', seatType: 'Upper Tier', price: 699 },
  { id: 30, seatNumber: 'D6', section: 'Balcony', seatType: 'Upper Tier', price: 699 },
  { id: 31, seatNumber: 'D7', section: 'Balcony', seatType: 'Upper Tier', price: 699 },
  { id: 32, seatNumber: 'D8', section: 'Balcony', seatType: 'Upper Tier', price: 699 },
];

